name: pollyboot
version: 0.0.1
author: Željko Kunica <zeljko.kunica@gmail.com>
description: Bootstrap components made in polymer
homepage: https://github.com/zeljkokunica/bootstrap-polymer.dart
dependencies:
    polymer: any
    bootjack: any
dev_dependencies:
  unittest: any
    